name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  loopcheck:
    strategy:
      matrix:
        scssfiles: [fileone,file2]
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          echo ${{ matrix.scssfiles }}.scss
